main: com.stardevllc.starspawners.plugin.StandaloneStarSpawnersPlugin
version: ${version}
api-version: 1.13
name: ${rootProject.name}
author: Firestar311
depend: [NBTAPI]
softdepend: [PlaceholderAPI]
commands:
  spawner: